### ISSUE TITLE
support whene item is opened from store

### ISSUE THREAD

**Issue by tomaskovacik** [morvy/AliExpress-copy-short-url#1]
script is not running when item is opened from store:

https://www.aliexpress.com/store/product/2PCS-Led-Dynamic-Side-Marker-Turn-Signal-For-Audi-A3-8L-97-03-A4-8D-94/3478017_33007952399.html

solution: add
```
// @include     *://www.aliexpress.com/store/product/*
```
but then link with reference amphtml is missing in source code, link is present when item is open with "direct" url:

https://www.aliexpress.com/item/2PCS-Led-Dynamic-Side-Marker-Turn-Signal-For-Audi-A3-8L-97-03-A4-8D-94/33007952399.html

solution is to use link
<link rel="alternate" media="only screen and (max-width: 640px)" href="https://m.aliexpress.com/item/*.html" />

(this one is used in new and also in old aliexpress site)

```
function tryShortUrl() {
    var amp = document.querySelector("link[media='only screen and (max-width: 640px)']");
```
document.querySelector("link[rel='alternate']") cannot be used as it has multiple occurrence in source code

**Comment by morvy** [comment]
fixed in 2.2.2
